
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    continue-on-error: false
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true
