debug: false

spring:
  application:
    name: jspy-server
  profiles:
    active: prod
  thymeleaf:
    cache: false

server:
  port: 8190


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true