profiles: dev

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    schema: classpath:db/schema.sql
    dbcp2:
      validation-query: SELECT 1
      pool-prepared-statements: true


  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true