profiles: prod

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./jspy
    platform: h2
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    username: aspyj
    password: 8190
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true
