debug: false

spring:
  application:
    name: jspy-server
  profiles:
    active: prod
  thymeleaf:
    cache: false
  cache:
    type: CAFFEINE
    caffeine:
      spec: initialCapacity=1048576,maximumSize=1073741824,expireAfterAccess=10m

server:
  port: 8190


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true


jspy:
  app-code: jSpyCons
  server-host: 127.0.0.1
  serverPort: 8190
  use-ssl: false
  watcher:
    enable: true