profiles: dev

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    validation-query: select 1
    test-while-idle: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true