debug: false

spring:
  application:
    name: jspy-server
  profiles:
    active: prod
  thymeleaf:
    cache: false
  cache:
    type: CAFFEINE
    caffeine:
      spec: initialCapacity=1048576,maximumSize=1073741824,weakKeys,weakValues,expireAfterAccess=10m

server:
  port: 8190


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true


jspy:
  appCode: zzy